---
apiVersion: v1
kind: Secret
metadata:
  name: otel-secrets
  namespace: "my namespace" #change me
type: Opaque
stringData:
  auth-token: "Authorization=Api-Token%20{token}" #change {token}
  tenant-url: "https://{your-environment-id}.live.dynatrace.com/api/v2/otlp" #change {environment-id}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: "my-application-namespace" #change me
spec:
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    # when using private registery modify and uncomment
    # latest image https://github.com/open-telemetry/opentelemetry-operator/pkgs/container/opentelemetry-operator%2Fautoinstrumentation-python
  # image: your-customized-auto-instrumentation-image:python
    env:
      # Python autoinstrumentation uses http/proto implementation by default
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: otel-secrets
            key: tenant-url
      - name: OTEL_EXPORTER_OTLP_HEADERS
        valueFrom: 
          secretKeyRef:
            name: otel-secrets
            key: auth-token
      - name: OTEL_LOGS_EXPORTER
        value: otlp_proto_http
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
  dotnet:
    env:
      # .net autoinstrumentation uses http/proto implementation by default
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        valueFrom:
          secretKeyRef:
            name: otel-secrets
            key: tenant-url
      - name: OTEL_EXPORTER_OTLP_HEADERS
        valueFrom: 
          secretKeyRef:
            name: otel-secrets
            key: auth-token