apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: my-instrumentation
  namespace: my-application-namespace
spec:
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  python:
    env:.
      # Python autoinstrumentation uses http/proto implementation by default
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://{your-environment-id}.live.dynatrace.com/api/v2/otlp
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: Authorization=Api-Token%20{token}
  dotnet:
    env:.
      # .net autoinstrumentation uses http/proto implementation by default
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: https://{your-environment-id}.live.dynatrace.com/api/v2/otlp
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: Authorization=Api-Token%20{token}