---
apiVersion: v1
kind: Secret
metadata:
  name: dynatrace-secrets
  namespace: my-application-namespace
type: Opaque
stringData:
  # replace the my-environment-id and my-token-value with the right values
  environment-id: "my-environment-id"
  api-token: "my-token-value"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: 'my application namespace'
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
  mode: sidecar # statefulset, daemonset, sidecar
  env:
    - name: environment-id
      valueFrom:
        secretKeyRef:
          name: dynatrace-secrets
          key: environment-id
    - name: API-TOKEN
      valueFrom:
        secretKeyRef:
           name: dynatrace-secrets
           key: api-token
  config: |
    receivers:

      # Data sources: traces, metrics, logs
      otlp:
        protocols:
          grpc:
          http:

      # Data sources: metrics
    # prometheus:
    #   config:
    #     scrape_configs:
    #       - job_name: otel-collector
    #         scrape_interval: 5s
    #         static_configs:
    #           - targets: [localhost:8888]

    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 25
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      otlphttp:
         endpoint: "https://${environment-id}.live.dynatrace.com/api/v2/otlp"
         headers:
           Authorization: "Api-Token ${API-TOKEN}"

      logging:

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [otlphttp]
        logs:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [logging]
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector-collector
  namespace: 'my application namespace'
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
  ports:
    - appProtocol: grpc
      name: otlp-grpc
      port: 4317
      protocol: TCP
      targetPort: 4317
    - appProtocol: http
      name: otlp-http
      port: 4318
      protocol: TCP
      targetPort: 4318
    - appProtocol: http
      name: otlp-http-legacy
      port: 55681
      protocol: TCP
      targetPort: 4318